/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientHome.java
 *
 * Created on Mar 19, 2014, 8:23:45 PM
 */
package com.gui;

import com.util.AppVariables;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Amritha
 */
public class ClientHome extends javax.swing.JFrame {

    /**
     * Creates new form ClientHome
     */
    public ClientHome() {
        initComponents();
        setIconImage(new ImageIcon(this.getClass().getResource("/com/icon/met_client_icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        loginButton = new javax.swing.JButton();
        newUserButton = new javax.swing.JButton();
        inboxButton = new javax.swing.JButton();
        composeButton = new javax.swing.JButton();
        decryptButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        clientMenuBar = new javax.swing.JMenuBar();
        loginMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        newuserMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem4 = new javax.swing.JMenuItem();
        inboxMenu = new javax.swing.JMenu();
        inboxMenuItem = new javax.swing.JMenuItem();
        encryptMenu = new javax.swing.JMenu();
        encodeDecodeMenuItem = new javax.swing.JMenuItem();
        decodeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metamorphic Client");
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/login_32.png"))); // NOI18N
        loginButton.setToolTipText("Login");
        loginButton.setFocusable(false);
        loginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(loginButton);

        newUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/add_user_32.png"))); // NOI18N
        newUserButton.setToolTipText("Add new user");
        newUserButton.setFocusable(false);
        newUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newUserButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(newUserButton);

        inboxButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/inbox_32.png"))); // NOI18N
        inboxButton.setToolTipText("Inbox");
        inboxButton.setEnabled(false);
        inboxButton.setFocusable(false);
        inboxButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inboxButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        inboxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboxButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(inboxButton);

        composeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/compose_32.png"))); // NOI18N
        composeButton.setToolTipText("Encode");
        composeButton.setEnabled(false);
        composeButton.setFocusable(false);
        composeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        composeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        composeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                composeButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(composeButton);

        decryptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/decrypt.png"))); // NOI18N
        decryptButton.setToolTipText("Decode");
        decryptButton.setEnabled(false);
        decryptButton.setFocusable(false);
        decryptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        decryptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(decryptButton);

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/logout_32.png"))); // NOI18N
        logoutButton.setToolTipText("Logout");
        logoutButton.setEnabled(false);
        logoutButton.setFocusable(false);
        logoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(logoutButton);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/meta.jpg"))); // NOI18N

        loginMenu.setText("File ");
        loginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuActionPerformed(evt);
            }
        });

        loginMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loginMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/login16.png"))); // NOI18N
        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        loginMenu.add(loginMenuItem);

        newuserMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        newuserMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/register_16.png"))); // NOI18N
        newuserMenuItem.setText("New User");
        newuserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newuserMenuItemActionPerformed(evt);
            }
        });
        loginMenu.add(newuserMenuItem);

        logoutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        logoutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/logout_16.png"))); // NOI18N
        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        loginMenu.add(logoutMenuItem);
        loginMenu.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/close_16.png"))); // NOI18N
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        loginMenu.add(jMenuItem4);

        clientMenuBar.add(loginMenu);

        inboxMenu.setText("Messages");

        inboxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        inboxMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/about2.png"))); // NOI18N
        inboxMenuItem.setText("Inbox");
        inboxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboxMenuItemActionPerformed(evt);
            }
        });
        inboxMenu.add(inboxMenuItem);

        clientMenuBar.add(inboxMenu);

        encryptMenu.setText("Encryption");

        encodeDecodeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        encodeDecodeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/encryption icon.png"))); // NOI18N
        encodeDecodeMenuItem.setText("Encode");
        encodeDecodeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encodeDecodeMenuItemActionPerformed1(evt);
            }
        });
        encryptMenu.add(encodeDecodeMenuItem);

        decodeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        decodeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/decryption icon.png"))); // NOI18N
        decodeMenuItem.setText("Decode");
        decodeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decodeMenuItemActionPerformed(evt);
            }
        });
        encryptMenu.add(decodeMenuItem);

        clientMenuBar.add(encryptMenu);

        setJMenuBar(clientMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        setSize(new java.awt.Dimension(581, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    new LoginFrame(this, rootPaneCheckingEnabled).setVisible(true);
    this.setTitle("Metamorphic Client-" + AppVariables.userName);
}//GEN-LAST:event_loginButtonActionPerformed
    
private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed
    new RegistrationForm(this, rootPaneCheckingEnabled).setVisible(true);
}//GEN-LAST:event_newUserButtonActionPerformed
    
private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
    int userOption = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
    if (userOption == JOptionPane.YES_OPTION) {
        enableComponents(false);
        setTitle("Metamorphic Client");
    }
}//GEN-LAST:event_logoutButtonActionPerformed
    
private void inboxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxButtonActionPerformed
    new InboxDialog(this, rootPaneCheckingEnabled).setVisible(true);
}//GEN-LAST:event_inboxButtonActionPerformed
    
private void composeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_composeButtonActionPerformed
    new EncryptDialog(this, rootPaneCheckingEnabled).setVisible(true);
}//GEN-LAST:event_composeButtonActionPerformed
    
private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
    new LoginFrame(this, rootPaneCheckingEnabled).setVisible(true);
    this.setTitle("Metamorphic Client-" + AppVariables.userName);
}//GEN-LAST:event_loginMenuItemActionPerformed
    
private void newuserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newuserMenuItemActionPerformed
    new RegistrationForm(this, rootPaneCheckingEnabled).setVisible(true);
}//GEN-LAST:event_newuserMenuItemActionPerformed
    
private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
    int userOption = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
    if (userOption == JOptionPane.YES_OPTION) {
        enableComponents(false);
        setTitle("Metamorphic Client");
    }
}//GEN-LAST:event_logoutMenuItemActionPerformed
    
private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    this.dispose();
}//GEN-LAST:event_jMenuItem4ActionPerformed
    
private void inboxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxMenuItemActionPerformed
    new InboxDialog(this, rootPaneCheckingEnabled).setVisible(true);
}//GEN-LAST:event_inboxMenuItemActionPerformed
    
private void encodeDecodeMenuItemActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encodeDecodeMenuItemActionPerformed1
    new EncryptDialog(this, rootPaneCheckingEnabled).setVisible(true);
}//GEN-LAST:event_encodeDecodeMenuItemActionPerformed1
    
    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        new DecryptDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_decryptButtonActionPerformed
    
    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
        new RegistrationForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_loginMenuActionPerformed
    
    private void decodeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decodeMenuItemActionPerformed
        new DecryptDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_decodeMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new ClientHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar clientMenuBar;
    private javax.swing.JButton composeButton;
    private javax.swing.JMenuItem decodeMenuItem;
    private javax.swing.JButton decryptButton;
    private javax.swing.JMenuItem encodeDecodeMenuItem;
    private javax.swing.JMenu encryptMenu;
    private javax.swing.JButton inboxButton;
    private javax.swing.JMenu inboxMenu;
    private javax.swing.JMenuItem inboxMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton loginButton;
    private javax.swing.JMenu loginMenu;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JButton newUserButton;
    private javax.swing.JMenuItem newuserMenuItem;
    // End of variables declaration//GEN-END:variables

    void enableComponents(boolean status) {
        loginButton.setEnabled(!status);
        logoutButton.setEnabled(status);
        composeButton.setEnabled(status);
        decryptButton.setEnabled(status);
        inboxButton.setEnabled(status);
        
        encodeDecodeMenuItem.setEnabled(status);
        decodeMenuItem.setEnabled(status);
        inboxMenuItem.setEnabled(status);
        logoutMenuItem.setEnabled(status);
        loginMenuItem.setEnabled(!status);
        
    }
    
}
